import PostLayout from '../../components/PostLayout'

export default function Post_defining_your_investment_horizon_can_lead_to_better_planning() {
  return (
    <PostLayout title="Defining your investment horizon can lead to better planning">
      <p className="post-date">March 29, 2026</p><p>When are you investing for?</p><p>Putting away money for the future is a smart thing to do, but not having it available when you need it, is not.</p><p>In America, the concept of retirement and saving for retirement gained traction in the 1930s with the introduction of social security. While there is no single retirement age, 65, when social security payments could be encashed, has been considered as that number.</p><p>in 1900, the 65+ group had only 3 million members, reflecting a nation with a young population, a mere 4 percent in a population size of 76 million.</p><p>Life expectancy crossed 65 in 1944. Therefore, till 1944, the probability of the retired adult enjoying the fruits of his savings was low, since the average person did not live beyond 65.</p><p>It crossed 70 in 1964. Even in 1964, only 5 years of post-retirement expenses were needed by most people. Creating a fund over 40 years of working life for a retirement period of 5 years did not create too many cases of distress.</p><p>However, with rising life expectancy, it is close to 80 now, the requirement has kept increasing, along with which has gone up the need to save a larger part of earnings during working years.</p><p>The same is the situation in India, with rising life expectancy. It is important to be able to project your likely lifespan in order that finances can be handled better. While it is not an exact science, the Actuaries Longevity Illustrator (“ALI”) helps you get an idea.</p><p>You can access it here: <a href="https://www.longevityillustrator.org/">https://www.longevityillustrator.org/</a></p><p>While life expectancy tables will tell you how long an individual of your age, gender, and health would be anticipated, on average, to live. And therein lies the catch. What you need to plan for is not how long the average person will live but how long YOU will live.</p><p>If you plan for the average and live less than it, you may be adequately funded for old age but may need to live a more penurious life when young than needed. On the other hand, if you plan for the average and live longer, you may run out of money in old age. It is a very personal choice but being aware of the consequences, hopefully, leads to more informed decision-making. There are other considerations as well. For instance, the funding provided may be to cover the old age of two people. In that case, the longevity assessment becomes even more complex.</p>
    </PostLayout>
  )
}
