import PostLayout from '../../components/PostLayout'

export default function Post_keep_the_cost_of_investing_low() {
  return (
    <PostLayout title="Keep the cost of investing low">
      <p className="post-date">April 7, 2026</p><p>Putting money to work is a task.</p><p>Just like you need to make choices between various investment options available, so do the people and institutions you entrust your money to. They have to put the money to work in order that they are able to generate a return from it and share it with you. If they just sit on the money, it will be a loss-making proposition for them.</p><h2>Putting money to work involves cost</h2><p>When you deposit money with a bank, they need to lend it out to companies and individuals who will be charged interest which becomes their return, a part of which gets shared with you based on agreed terms. The cost of this effort is factored into the interest rate promised on the deposit.</p><p>When you deposit money with a fund, they need to research markets, move money around and make choices in line with the objective of the fund. Many funds charge a management fee to their investors on an annual basis in order to pay for these costs.</p><p>Financial advisors also cost money.</p><p>Most people have a long investment horizon, from the time they start working, till the time they retire from active work. Annual and other fees over a long horizon become substantial.</p><p>Hence, keeping the investment cost low can itself deliver a huge benefit over several decades.</p><h2>The impact of lower cost investing</h2><p>Let us take an example of two funds, A and B, that deliver the same return year after year. The management fee charged by one is substantially lower than the other. How does it impact an investor over a period of time? </p><p><strong>Table: Comparative earnings difference between funds with different costs</strong></p><div className="table-container">
        <table><tr><th></th><th>Fund A</th><th>Fund B</th></tr><tr><td>Gross return p.a.</td><td>10%</td><td>10%</td></tr><tr><td>Management fee p.a.</td><td>1.25%</td><td>0.25%</td></tr><tr><td>Net return to investor p.a.</td><td>8.75%</td><td>9.75%</td></tr><tr><td>In 10 years, an initial investment of ₹ 10,000 will amount to</td><td>₹ 23,136</td><td>₹ 25,354</td></tr><tr><td>Investor earnings over 10 years</td><td>₹ 13,136</td><td>₹ 15,354</td></tr></table>
      </div><p>Here is another illustration over a longer period of 50 years which demonstrates the additional value created by a fund which costs 1% lower than another similar fund. The initial investment is ₹ 10,000 and the cost difference between the two funds is 1%.</p><p><strong>Table: Incremental value created over time</strong></p><div className="table-container">
        <table><tr><th>Initial Investment</th><th>₹ 10,000</th></tr><tr><td>Investment Period in Years</td><td>50</td></tr><tr><td>Investment Return Direct Fund</td><td>10.00%</td></tr><tr><td>Additional Fees of Regular Fund</td><td>1.00%</td></tr><tr><td>Investment Return Regular Fund</td><td>9.00%</td></tr><tr><td>Final Value Direct Fund</td><td> ₹ 11,73,909 </td></tr><tr><td>Final Value Regular Fund</td><td> ₹ 7,43,575 </td></tr><tr><td>Additional Value</td><td> ₹ 4,30,333 </td></tr></table>
      </div><p>What do we see?</p><p>Taking the higher-cost fund (Regular Fund) as the base case, the lower-cost fund (Direct Fund) has delivered 57% more in terms of gross earnings (₹ 4,30,333 as a percentage of ₹ 7,43,575) to the investor over a 50-year period.</p><p>The following table illustrates how the additional value changes over time.</p><p><strong>Table: Additional value created over different time horizons</strong></p><div className="table-container">
        <table><tr><th>Investment Period in Years</th><th>Additional Value (₹)</th></tr><tr><td>1</td><td> 100 </td></tr><tr><td>2</td><td> 219 </td></tr><tr><td>3</td><td> 360 </td></tr><tr><td>5</td><td> 719 </td></tr><tr><td>10</td><td> 2,264 </td></tr><tr><td>15</td><td> 5,348 </td></tr><tr><td>20</td><td> 11,231 </td></tr><tr><td>25</td><td> 22,116 </td></tr><tr><td>30</td><td> 41,817 </td></tr><tr><td>40</td><td> 1,38,498 </td></tr><tr><td>50</td><td> 4,30,333 </td></tr></table>
      </div><h2>How to do low-cost investing</h2><p>Here are some strategies for low-cost investing:</p><ul><li>Choose low-cost index funds</li><li>Choose inactive over active funds</li><li>Choose Direct over Regular funds </li><li>Choose funds with a large corpus so that the management cost is more widely shared and each investor’s share is low</li><li>Avoid frequent trading – each time you trade a transaction cost is incurred</li><li>Choose funds with a history of low management fees</li><li>If you trade directly, use discount brokerages, which typically operate online</li><li>Stay away from high-cost, structured or exotic products</li><li>Maximize post-tax returns through leveraging tax-saving instruments </li></ul><h2>Conclusion</h2><p>The objective is not to say that one should ignore high-cost investments even if they are delivering great returns. The objective is to sensitize investors about the material impact on returns that the cost passed on to investors by a fund can have. Hence, it should be part of the variable-set to be evaluated before choosing a fund.</p>
    </PostLayout>
  )
}
