import PostLayout from '../../components/PostLayout'

export default function Post_equity_linked_saving_scheme() {
  return (
    <PostLayout title="Equity Linked Saving Scheme (ELSS)">
      <p className="post-date">July 20, 2026</p><p>It is a type of mutual fund scheme primarily investing in equity and equity-related instruments, and it offers tax benefits under Section 80C of the Income Tax Act, 1961.</p><h2>Features</h2><ul><li>A minimum of 80% of the total investible corpus is invested in equity and equity-related instruments</li><li>The fund invested in equity in a diversified manner – across different market capitalization, themes and sectors.</li><li>There is no maximum tenure of investment. However, there is a lock-in period of 3 years.</li><li>Tax exemption on the invested amount available under section 80C upto ₹ 1.5 lakh.</li><li>Income is treated as Long Term Capital Gain and taxed as per the prevalent tax rules. These gains are tax-free up to ₹ 1 lakh per year, and any earnings beyond this amount are subject to a 10% long-term capital gains tax.</li><li>It allows the investor to start investing as low as ₹ 500.</li><li>It allows the investor to invest in lumpsum amount or in the form of SIPs.</li></ul><h2>Return and Risk</h2><p>ELSS funds carry higher risk compared to traditional tax-saving options like PPF and NSC due to their equity exposure. However, they also offer the potential for higher returns over the long-term, aligning with the higher risk-reward profile of equities.</p><p>The strategy of diversification across companies and sectors helps in mitigating the risk to some extent. However, the inherent risk present in equities as an investment class continues.</p><h2>ELSS vs NPS</h2><div className="table-container">
        <table><tr><th></th><th>ELSS</th><th>NPS</th></tr><tr><td>Nature of investment</td><td>A type of mutual fund that primarily invests in equity and equity-related instruments. It offers the potential for high returns but also carries higher market risk due to equity exposure.</td><td>A government-sponsored pension scheme that offers a mix of equity, corporate bonds, government securities, and alternative assets. It is designed for retirement planning and offers a diversified portfolio with varying risk profiles based on the investment option</td></tr><tr><td>Tax implications</td><td>Investments qualify for tax deductions under Section 80C of the Income Tax Act, up to a maximum of ₹1.5 lakh in a financial year. Additionally, long-term capital gains (LTCG) up to ₹1 lakh from ELSS are tax-exempt.</td><td>Contributions to NPS Tier I account qualify for tax deductions under Section 80CCD(1) within the overall limit of ₹1.5 lakh under Section 80C. An additional deduction of up to ₹50,000 is available under Section 80CCD(1B). Withdrawals from the mandatory NPS Tier 1 are not taxed.</td></tr><tr><td>Lock-in period</td><td>ELSS has a lock-in period of three years, which is the shortest among tax-saving investment options under Section 80C.</td><td>NPS has a longer lock-in period, with investments in the Tier I account being locked in until retirement age, although partial withdrawals are allowed under certain conditions.</td></tr><tr><td>Flexibility</td><td>ELSS offers flexibility in terms of investment amount and withdrawal options after the lock-in period. Investors can choose to invest through lump-sum or systematic investment plans (SIPs).</td><td>NPS offers flexibility in choosing investment options, allocation among asset classes, and fund managers. Withdrawals from the Tier I account are restricted, with conditions attached. Withdrawals can be freely made from the Tier 2 account.</td></tr></table>
      </div><h2>Comparison of returns</h2><h3>ELSS</h3><p>Trailing returns delivered by the 10 largest funds 9(by AUM) as per data tracked by <a href="https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/elss.html">Moneycontrol.com</a>:</p><div className="table-container">
        <table><tr><th>Scheme Name</th><th>AuM (Cr)</th><th>1Y</th><th>5Y</th><th>10Y</th></tr><tr><td>Axis ELSS Tax Saver Fund - Direct Plan - Growth</td><td>36,257.53</td><td>5%</td><td>18%</td><td>13%</td></tr><tr><td>SBI ELSS Tax Saver Fund - Direct Plan - Growth</td><td>30,616.22</td><td>3%</td><td>28%</td><td>15%</td></tr><tr><td>Mirae Asset ELSS Tax Saver Fund - Direct Plan - Growth</td><td>26,537.48</td><td>6%</td><td>24%</td><td>-</td></tr><tr><td>DSP ELSS Tax Saver Fund - Direct Plan - Growth</td><td>17,427.57</td><td>5%</td><td>26%</td><td>17%</td></tr><tr><td>HDFC ELSS Tax saver - Direct Plan – Growth</td><td>16,908.00</td><td>7%</td><td>27%</td><td>14%</td></tr><tr><td>Aditya Birla Sun Life ELSS Tax Saver Fund - Direct Plan - Growth</td><td>15,869.72</td><td>4%</td><td>16%</td><td>12%</td></tr><tr><td>Nippon India ELSS Tax Saver Fund - Direct Plan - Growth</td><td>15,623.15</td><td>1%</td><td>25%</td><td>11%</td></tr><tr><td>ICICI Prudential ELSS Tax Saver Fund - Direct Plan - Growth</td><td>14,660.64</td><td>5%</td><td>23%</td><td>14%</td></tr><tr><td>Quant ELSS Tax Saver Fund - Direct Plan - Growth</td><td>11,922.65</td><td>-9%</td><td>33%</td><td>22%</td></tr><tr><td>Canara Robeco ELSS Tax Saver Fund - Direct Plan - Growth</td><td>9,102.87</td><td>4%</td><td>23%</td><td>15%</td></tr></table>
      </div><h3>NPS</h3><p>Trailing returns (% p.a.) delivered by various Pension Fund Managers for the Tier 1 E (Equity) Scheme over a 10-year period ending on 11th July, 2025, as published by the <a href="https://npstrust.org.in/weekly-snapshot-nps-schemes">NPS Trust</a>, are shown below:</p><div className="table-container">
        <table><tr><th>Pension Fund</th><th>AUM<br />(₹ Crs)</th><th>1 Year</th><th>5 Years</th><th>10 Years</th></tr><tr><td>Aditya Birla Sun Life Pension Fund Management Limited</td><td> 1,746.66 </td><td>3.42%</td><td>20.03%</td><td>NA</td></tr><tr><td>Axis Pension Fund Management Limited</td><td> 4,266.92 </td><td>3.07%</td><td>NA</td><td>NA</td></tr><tr><td>HDFC Pension Fund Management Ltd.</td><td> 60,891.46 </td><td>4.47%</td><td>21.32%</td><td>13.40%</td></tr><tr><td>ICICI Pru. Pension Fund Mgmt Co. Ltd.</td><td> 21,908.75 </td><td>3.46%</td><td>22.33%</td><td>13.14%</td></tr><tr><td>Kotak Mahindra Pension Fund Ltd.</td><td> 3,209.39 </td><td>5.50%</td><td>21.99%</td><td>13.33%</td></tr><tr><td>LIC Pension Fund Ltd.</td><td> 6,960.23 </td><td>3.71%</td><td>21.83%</td><td>12.27%</td></tr><tr><td>SBI Pension Funds Pvt. Ltd</td><td> 23,501.93 </td><td>-0.36%</td><td>19.48%</td><td>12.01%</td></tr><tr><td>Tata Pension Fund Management Pvt. Ltd.</td><td> 2,002.39 </td><td>1.77%</td><td>NA</td><td>NA</td></tr><tr><td>UTI Pension Fund Ltd.</td><td> 4,727.24 </td><td>3.10%</td><td>22.36%</td><td>13.37%</td></tr><tr><td>DSP Pension Fund Managers Private Limited</td><td> 2,087.90 </td><td>12.24%</td><td>NA</td><td>NA</td></tr></table>
      </div><h2>Conclusion</h2><p>The returns delivered by most NPS funds are within a narrow range. ELSS funds, on the other hand, display a greater variance in performance. Thus:</p><ul><li>ELSS funds have the capacity to deliver better gross returns than NPS funds.</li><li>NPS Tier 1 has tax benefits on withdrawals that are unlimited while gains on ELSS liquidation are tax-exempt only upto ₹ 1 lakh in a year. Thus, ELSS should be the preferred investment for smaller amounts and NPS for larger.</li><li>Where the investment is being made as a means to achieving the allocation to equity, ELSS should be prioritized over NPS. </li></ul>
    </PostLayout>
  )
}
